
# SEO settings
title: cve-search - tool-set to perform local searches for known vulnerabilities
description: "cve-search is a tool to import CVE (Common Vulnerabilities and Exposures) and CPE (Common Platform Enumeration) into a MongoDB to facilitate search and processing of CVEs."
keywords: "cve, cve-search, vulnerability, software vulnerability, vulnerability assessment, cpe, software vulnerabilities"
url: https://www.cve-search.org
#baseurl: "/"
baseurl: null

#google_analytics: UA-52446115-1
#repo: http://github.com/cve-search
#disqus_shortname: "nandothemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
#comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : cve-search core team
  github   : http://github.com/cve-search
#  twitter  : http://twitter.com/nandomoreirame
#  facebook : http://facebook.com/fernando.dev
#  linkedin : http://linkedin.com/in/nandomoreirame

# social settings
#og_locale: "pt_BR"
#twitter_card: "summary_large_image"
#twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
